language: node_js
node_js: node
services: mysql
before_install:
  - mysql -e 'CREATE DATABASE test_db;'


# If you want to use PostgreSQL 

# before_install:
#   - psql -U postgres -c 'CREATE DATABASE "test_db";'
#   addons:
#     postgresql:"10"
#     apt:
#       packages:
#         - postgresql-10
#         -postgresql-client-10
#         env:
#           global:
#             -PGPORT=5433             