language: node_js
node_js: node
services: mysql
before_install:
  - mysql -e 'CREATE DATABASE test_db;'
#before_script: mysql test_db < ../db/noteful.sql
  #- psql -U postgres -c 'CREATE DATABASE "noteful-test";'



# before_script:
#   - psql -c 'CREATE DATABASE noteful-test;' -U dev
#   addons:
#     postgresql:"10"
#     apt:
#       packages:
#         - postgresql-10
#         -postgresql-client-10
#         env:
#           global:
#             -PGPORT=5433
             